sudo: required

group: edge

services:
  - docker

env:
  global:
    - VERSION=${VERSION:-0.11.0}

jobs:
  include:
    - stage: build
      script:
        - make

    - stage: test
      script:
        - make compose-file
        - docker-compose build
        - docker-compose up -d
        - sleep 30s
        - make test
        - docker-compose down

    - stage: push docker image
      if: branch = master
      script:
        - make
        - docker tag ${USER}/carbon-relay-ng:latest ${DOCKER_USERNAME}/docker-carbon-relay-ng:latest
        - docker tag ${USER}/carbon-relay-ng:latest ${DOCKER_USERNAME}/docker-carbon-relay-ng:${VERSION}
        #
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        #
        - docker push ${DOCKER_USERNAME}/docker-carbon-relay-ng:latest
        - docker push ${DOCKER_USERNAME}/docker-carbon-relay-ng:${VERSION}
        #
        - docker logout
