---
version: '3.3'

services:

  graphite:
    restart: always
    image: bodsch/docker-graphite:1.1.4
    container_name: graphite
    hostname: graphite

  carbon-relay:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TYPE=${BUILD_TYPE}
        - VERSION=${VERSION}
    container_name: carbon-relay
    hostname: carbon-relay
    ports:
      - 2003:2003
      - 2004:2004
      - 8081:8081
    links:
      - graphite
