
name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  build:
    name: build graphite ${{ matrix.carbon_relay_version }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        carbon_relay_version:
          - 0.14.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: |
          make build
        env:
          PY_COLORS: '1'
          VERSION: ${{ matrix.carbon_relay_version }}

      - name: Test Docker images
        run: |
          make compose-file
          docker-compose build
          docker-compose up -d
          sleep 30s
          make test
          docker-compose down
        env:
          PY_COLORS: '1'
          VERSION: ${{ matrix.carbon_relay_version }}
