name: Push

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 18 * * sun'

jobs:
  push:
    name: push graphite ${{ matrix.carbon_relay_version }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        carbon_relay_version:
          - 0.14.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          make build
        env:
          VERSION: ${{ matrix.carbon_relay_version }}

      - name: Push Docker image to Docker Hub
        run: |
          # Login on dockerhub.io before pushing
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          # Pushing image to dockerhub
          #
          # docker tag  ${USER}/carbon-relay-ng:latest bodsch/docker-carbon-relay-ng:latest
          # docker push bodsch/docker-carbon-relay-ng:latest
          #
          docker tag  ${USER}/carbon-relay-ng:latest bodsch/docker-carbon-relay-ng:${VERSION}
          docker push bodsch/docker-carbon-relay-ng:${VERSION}
          #
          docker logout
        env:
          VERSION: ${{ matrix.carbon_relay_version }}


      # - name: Push Docker image to Github Docker registry
      #   run: |
      #     # Login on Github Docker registry before pushing
      #     echo "${{ secrets.GH_REGISTRY_TOKEN }}" | docker login docker.pkg.github.com -u bodsch --password-stdin
      #     # Pushing image to Github Docker registry
      #     #
      #     docker tag  ${USER}/carbon-relay-ng:latest bodsch/carbon-relay-ng:latest
      #     docker push \
      #       docker.pkg.github.com/bodsch/carbon-relay-ng:latest
      #     #
      #     docker tag  ${USER}/carbon-relay-ng:latest bodsch/carbon-relay-ng:${VERSION}
      #     docker push \
      #       docker.pkg.github.com/bodsch/carbon-relay-ng:${VERSION}
      #     #
      #   env:
      #     VERSION: ${{ matrix.carbon_relay_version }}
